"use client";

import { useEffect, useState } from "react";

type Option = { id: string; purchaseRequestReference: string; selectedSupplierName: string; currencyCode: string; selectedEvaluatedTotal: number; lineLabel: string; expectedDeliveryDate: string };
type Props = { action: (formData: FormData) => void | Promise<void> };

export function PurchaseOrderCreateComposer({ action }: Props) {
  const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [options, setOptions] = useState<Option[]>([]); const [total, setTotal] = useState(0); const [pages, setPages] = useState(1); const [selectedId, setSelectedId] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(false); fetch(`/api/purchase-orders/approved-recommendations?query=${encodeURIComponent(query)}&page=${page}&pageSize=25${selectedId ? `&selectedId=${encodeURIComponent(selectedId)}` : ""}`, { signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((result) => { setOptions(result.options ?? []); setTotal(result.total ?? 0); setPages(Math.max(1, result.pageCount ?? 1)); setLoading(false); }).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setLoading(false); setError(true); }); return () => controller.abort(); }, [query, page, selectedId, retry]);
  const selected = options.find((item) => item.id === selectedId) ?? options[0];
  const input = "min-h-11 rounded-md border border-slate-300 px-3 py-2 text-sm";
  return <form action={action} className="grid gap-3" aria-busy={loading}>
    <label className="grid gap-1 text-sm font-medium text-slate-700">Search approved recommendations<input className={input} value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="PR reference, supplier, or quote" /></label>
    {loading ? <p className="text-xs font-semibold text-slate-600" role="status">Loading approved recommendations…</p> : null}
    {error ? <div className="flex flex-wrap items-center gap-2" role="alert"><p className="text-sm text-rose-700">Recommendation lookup is unavailable.</p><button type="button" className="min-h-11 rounded-md border border-rose-300 px-3 text-sm font-semibold" onClick={() => setRetry((value) => value + 1)}>Retry</button></div> : null}
    {!loading && !error && options.length === 0 ? <p className="rounded-lg border border-dashed border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">No approved supplier recommendations match this search.</p> : null}
    {options.length > 0 ? <><label className="grid gap-1 text-sm font-medium text-slate-700">Approved recommendation<select className={input} name="quotationRecommendationId" value={selectedId || selected?.id} onChange={(event) => setSelectedId(event.target.value)} required>{options.map((option) => <option key={option.id} value={option.id}>{option.purchaseRequestReference} / {option.selectedSupplierName} / {option.currencyCode} {option.selectedEvaluatedTotal.toFixed(2)}</option>)}</select></label><div className="rounded-lg border border-blue-100 bg-blue-50 p-3 text-sm text-slate-700"><p className="font-semibold text-slate-900">{selected?.lineLabel}</p><p className="mt-1">Expected delivery defaults to {selected?.expectedDeliveryDate}.</p></div><div className="flex flex-col gap-2 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>{total} approved recommendation{total === 1 ? "" : "s"} · page {page} of {pages}</span><span className="flex shrink-0 flex-wrap gap-2"><button type="button" className="min-h-11 shrink-0 whitespace-nowrap rounded-md border px-3" disabled={page <= 1 || loading} onClick={() => setPage(page - 1)}>Previous</button><button type="button" className="min-h-11 shrink-0 whitespace-nowrap rounded-md border px-3" disabled={page >= pages || loading} onClick={() => setPage(page + 1)}>Next</button></span></div><button className="inline-flex min-h-11 items-center justify-center rounded-md bg-blue-600 px-4 text-sm font-semibold text-white" disabled={loading}>Create Draft PO</button></> : null}
  </form>;
}
