"use client";

import { useState } from "react";

const MAX_ADDED_LINES = 100;

type Item = { id: string; code: string; name: string };
type Uom = { id: string; code: string; name: string };
type SubRecipe = { id: string; code: string; name: string; versionNo: number; servingUomCode: string };

export function RecipeRevisionAddLinesEditor({ items, uoms, subRecipes, defaultUomId, firstSortOrder }: { items: readonly Item[]; uoms: readonly Uom[]; subRecipes: readonly SubRecipe[]; defaultUomId: string; firstSortOrder: number }) {
  const [ingredientLines, setIngredientLines] = useState([1]);
  const [subRecipeLines, setSubRecipeLines] = useState([1]);
  const add = (kind: "ingredient" | "subRecipe") => kind === "ingredient" ? setIngredientLines((lines) => lines.length >= MAX_ADDED_LINES ? lines : [...lines, lines.length + 1]) : setSubRecipeLines((lines) => lines.length >= MAX_ADDED_LINES ? lines : [...lines, lines.length + 1]);
  const remove = (kind: "ingredient" | "subRecipe", slot: number) => kind === "ingredient" ? setIngredientLines((lines) => lines.length === 1 ? lines : lines.filter((line) => line !== slot)) : setSubRecipeLines((lines) => lines.length === 1 ? lines : lines.filter((line) => line !== slot));

  return <>
    <section className="ogfi-data-surface overflow-hidden"><div className="ogfi-section-header"><div><h2 className="text-lg font-bold text-slate-950">Add ingredient lines</h2><p className="text-sm text-slate-500">Add ingredients scoped to this revision.</p></div><button className="inline-flex min-h-10 items-center justify-center rounded-md border border-blue-200 bg-blue-50 px-3 text-sm font-semibold text-blue-700 hover:bg-blue-100 disabled:cursor-not-allowed disabled:border-slate-200 disabled:bg-slate-100 disabled:text-slate-400" disabled={ingredientLines.length >= MAX_ADDED_LINES} onClick={() => add("ingredient")} type="button">Add ingredient</button></div><div className="grid gap-3 p-4">{ingredientLines.map((slot, index) => <fieldset key={slot} className="grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 md:grid-cols-[5rem_minmax(0,1.3fr)_8rem_10rem_minmax(0,1fr)_auto] md:items-end"><legend className="sr-only">New ingredient {index + 1}</legend><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Order<input className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newLine.${slot}.sortOrder`} type="number" min="1" max="100" defaultValue={firstSortOrder + index} /></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Ingredient<select className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newLine.${slot}.itemId`} defaultValue=""><option value="">Select ingredient</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} / {item.name}</option>)}</select></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Quantity<input className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newLine.${slot}.quantity`} type="number" min="0.000001" step="0.000001" /></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">UOM<select className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newLine.${slot}.uomId`} defaultValue={defaultUomId}>{uoms.map((uom) => <option key={uom.id} value={uom.id}>{uom.code} / {uom.name}</option>)}</select></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Preparation note<input className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newLine.${slot}.preparationNote`} placeholder="Optional" /></label><button className="inline-flex min-h-10 items-center justify-center rounded-md px-3 text-sm font-semibold text-rose-700 hover:bg-rose-50 disabled:cursor-not-allowed disabled:text-slate-400" disabled={ingredientLines.length === 1} onClick={() => remove("ingredient", slot)} type="button">Remove</button></fieldset>)}</div></section>
    <section className="ogfi-data-surface overflow-hidden"><div className="ogfi-section-header"><div><h2 className="text-lg font-bold text-slate-950">Add sub-recipe lines</h2><p className="text-sm text-slate-500">Link published prep or sub-recipe versions without changing their source records.</p></div><button className="inline-flex min-h-10 items-center justify-center rounded-md border border-blue-200 bg-blue-50 px-3 text-sm font-semibold text-blue-700 hover:bg-blue-100 disabled:cursor-not-allowed disabled:border-slate-200 disabled:bg-slate-100 disabled:text-slate-400" disabled={subRecipeLines.length >= MAX_ADDED_LINES} onClick={() => add("subRecipe")} type="button">Add sub-recipe</button></div><div className="grid gap-3 p-4">{subRecipeLines.map((slot, index) => <fieldset key={slot} className="grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-3 md:grid-cols-[5rem_minmax(0,1.5fr)_8rem_minmax(0,1fr)_auto] md:items-end"><legend className="sr-only">New sub-recipe {index + 1}</legend><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Order<input className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newSubRecipe.${slot}.sortOrder`} type="number" min="1" max="100" defaultValue={firstSortOrder + ingredientLines.length + index} /></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Sub-recipe<select className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newSubRecipe.${slot}.subRecipeVersionId`} defaultValue=""><option value="">Select sub-recipe</option>{subRecipes.map((recipe) => <option key={recipe.id} value={recipe.id}>{recipe.code} / {recipe.name} / v{recipe.versionNo} / {recipe.servingUomCode}</option>)}</select></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Quantity<input className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newSubRecipe.${slot}.quantity`} type="number" min="0.000001" step="0.000001" /></label><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Preparation note<input className="min-h-10 rounded-md border border-slate-300 bg-white px-3 py-2 text-slate-950" name={`newSubRecipe.${slot}.preparationNote`} placeholder="Optional" /></label><button className="inline-flex min-h-10 items-center justify-center rounded-md px-3 text-sm font-semibold text-rose-700 hover:bg-rose-50 disabled:cursor-not-allowed disabled:text-slate-400" disabled={subRecipeLines.length === 1} onClick={() => remove("subRecipe", slot)} type="button">Remove</button></fieldset>)}</div></section>
  </>;
}
