"use client";

import { useMemo, useState, type FormEvent } from "react";
import { PURCHASE_REQUEST_MAX_LINES } from "@/lib/workflowLimits";

type QuoteRequestLine = { id: string; lineNumber: number; itemName: string | null; description: string; requestedQty: number; uomId: string | null; uomCode: string; purpose: string };
type QuoteRequestOption = { id: string; publicReference: string; requiredDate: string; lines: QuoteRequestLine[] };
type SupplierOption = { id: string; supplierCode: string; legalName: string };
type UomOption = { id: string; uomCode: string; uomName: string };
type Props = { requests: QuoteRequestOption[]; suppliers: SupplierOption[]; uoms: UomOption[]; action: (formData: FormData) => void | Promise<void> };
type DraftLine = { sourcePrLineId: string; lineNumber: number; label: string; requestSummary: string; quantity: string; uomId: string; unitPrice: string; leadTimeDays: string; availabilityStatus: string; notes: string };

function draftLines(request: QuoteRequestOption | undefined, uoms: UomOption[]): DraftLine[] { return request?.lines.map((line) => ({ sourcePrLineId: line.id, lineNumber: line.lineNumber, label: line.itemName ?? line.description, requestSummary: `${line.requestedQty} ${line.uomCode} / ${line.purpose}`, quantity: String(line.requestedQty), uomId: line.uomId ?? uoms.find((uom) => uom.uomCode === line.uomCode)?.id ?? uoms[0]?.id ?? "", unitPrice: "", leadTimeDays: "", availabilityStatus: "Available", notes: "" })) ?? []; }

export function SupplierQuoteLinesEditor({ requests, suppliers, uoms, action }: Props) {
  const hasFormOptions = requests.length > 0 && suppliers.length > 0 && uoms.length > 0;
  const [selectedRequestId, setSelectedRequestId] = useState(requests[0]?.id ?? "");
  const [idempotencyKey, setIdempotencyKey] = useState(() => crypto.randomUUID());
  const [lines, setLines] = useState<DraftLine[]>(() => draftLines(requests[0], uoms));
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [errors, setErrors] = useState<number[]>([]);
  const selected = lines[selectedIndex] ?? lines[0];
  const incomplete = useMemo(() => lines.flatMap((line, index) => Number(line.quantity) > 0 && line.uomId && Number(line.unitPrice) > 0 && line.availabilityStatus.trim() ? [] : [index]), [lines]);
  const input = "min-h-10 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-950";
  function selectRequest(id: string) { setSelectedRequestId(id); setIdempotencyKey(crypto.randomUUID()); setLines(draftLines(requests.find((request) => request.id === id), uoms)); setSelectedIndex(0); setErrors([]); }
  function update(values: Partial<DraftLine>) { setLines((current) => current.map((line, index) => index === selectedIndex ? { ...line, ...values } : line)); }
  function submit(event: FormEvent<HTMLFormElement>) { if (incomplete[0] === undefined) return; event.preventDefault(); setErrors(incomplete); setSelectedIndex(incomplete[0]); }

  return <form action={action} className="flex h-full min-h-0 flex-col" onSubmit={submit}>
    <input name="idempotencyKey" type="hidden" value={idempotencyKey} readOnly />
    {lines.map((line) => <input key={`source-${line.sourcePrLineId}`} name="sourcePrLineId" type="hidden" value={line.sourcePrLineId} readOnly />)}
    {lines.map((line) => <input key={`qty-${line.sourcePrLineId}`} name="lineQuantity" type="hidden" value={line.quantity} readOnly />)}
    {lines.map((line) => <input key={`uom-${line.sourcePrLineId}`} name="lineUomId" type="hidden" value={line.uomId} readOnly />)}
    {lines.map((line) => <input key={`price-${line.sourcePrLineId}`} name="lineUnitPrice" type="hidden" value={line.unitPrice} readOnly />)}
    {lines.map((line) => <input key={`lead-${line.sourcePrLineId}`} name="lineLeadTimeDays" type="hidden" value={line.leadTimeDays} readOnly />)}
    {lines.map((line) => <input key={`availability-${line.sourcePrLineId}`} name="lineAvailabilityStatus" type="hidden" value={line.availabilityStatus} readOnly />)}
    {lines.map((line) => <input key={`notes-${line.sourcePrLineId}`} name="lineNotes" type="hidden" value={line.notes} readOnly />)}
    <div className="shrink-0 border-b border-slate-200 p-4"><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-sm font-medium text-slate-700">Purchase Request<select className={input} name="purchaseRequestId" value={selectedRequestId} disabled={!hasFormOptions} onChange={(event) => selectRequest(event.target.value)} required>{requests.map((request) => <option key={request.id} value={request.id}>{request.publicReference} / {request.lines.length} line{request.lines.length === 1 ? "" : "s"}</option>)}</select></label><label className="grid gap-1 text-sm font-medium text-slate-700">Supplier<select className={input} name="supplierId" disabled={!hasFormOptions} required>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.supplierCode} / {supplier.legalName}</option>)}</select></label><label className="grid gap-1 text-sm font-medium text-slate-700">Quote reference<input className={input} name="quoteReference" disabled={!hasFormOptions} required /></label><label className="grid gap-1 text-sm font-medium text-slate-700">Quote date<input className={input} name="quoteDate" type="date" disabled={!hasFormOptions} required /></label><label className="grid gap-1 text-sm font-medium text-slate-700">Valid until<input className={input} name="validityDate" type="date" disabled={!hasFormOptions} /></label></div></div>
    <div className="flex min-h-0 flex-1 flex-col lg:grid lg:grid-cols-[minmax(19rem,0.72fr)_minmax(0,1.28fr)]">
      <aside className="min-h-0 border-b border-slate-200 lg:border-b-0 lg:border-r"><div className="border-b border-slate-200 px-4 py-3"><h3 className="text-sm font-bold text-slate-950">Quoted lines</h3><p className="text-xs font-semibold text-slate-500">{lines.length} / {PURCHASE_REQUEST_MAX_LINES}{errors.length ? ` / ${errors.length} need attention` : ""}</p></div><div className="max-h-48 divide-y divide-slate-100 overflow-y-auto lg:h-[calc(100%-4.5rem)] lg:max-h-none">{lines.map((line, index) => { const invalid = errors.includes(index); return <button key={line.sourcePrLineId} className={`grid min-h-14 w-full grid-cols-[2rem_minmax(0,1fr)_auto] items-center gap-2 px-4 py-2 text-left ${index === selectedIndex ? "bg-blue-50" : "hover:bg-slate-50"}`} onClick={() => setSelectedIndex(index)} type="button"><span className="text-sm font-bold text-slate-500">{line.lineNumber}</span><span className="min-w-0"><span className="block truncate text-sm font-bold text-slate-950">{line.label}</span><span className="block truncate text-xs text-slate-500">{line.unitPrice ? `${line.quantity} @ ${line.unitPrice}` : line.requestSummary}</span></span><span className={invalid ? "text-xs font-bold text-rose-700" : "text-xs font-bold text-slate-500"}>{invalid ? "Needs info" : line.unitPrice ? "Ready" : "Unpriced"}</span></button>; })}</div></aside>
      <section className="min-h-0 overflow-y-auto p-4">{selected ? <><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-slate-500">Editing line {selectedIndex + 1} of {lines.length}</p><h3 className="text-lg font-bold text-slate-950">{selected.label}</h3><p className="text-sm text-slate-500">{selected.requestSummary}</p></div><div className="flex gap-2"><button className="min-h-10 rounded-md border border-slate-300 px-3 text-sm font-semibold disabled:text-slate-400" disabled={selectedIndex === 0} onClick={() => setSelectedIndex(selectedIndex - 1)} type="button">Previous</button><button className="min-h-10 rounded-md border border-slate-300 px-3 text-sm font-semibold disabled:text-slate-400" disabled={selectedIndex === lines.length - 1} onClick={() => setSelectedIndex(selectedIndex + 1)} type="button">Next</button></div></div><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium text-slate-700">Quoted quantity<input className={input} min="0.000001" step="0.000001" type="number" value={selected.quantity} onChange={(event) => update({ quantity: event.target.value })} /></label><label className="grid gap-1 text-sm font-medium text-slate-700">UOM<select className={input} value={selected.uomId} onChange={(event) => update({ uomId: event.target.value })}>{uoms.map((uom) => <option key={uom.id} value={uom.id}>{uom.uomCode} / {uom.uomName}</option>)}</select></label><label className="grid gap-1 text-sm font-medium text-slate-700">Unit price<input className={input} min="0.000001" step="0.000001" type="number" value={selected.unitPrice} onChange={(event) => update({ unitPrice: event.target.value })} /></label><label className="grid gap-1 text-sm font-medium text-slate-700">Lead days<input className={input} min="0" type="number" value={selected.leadTimeDays} onChange={(event) => update({ leadTimeDays: event.target.value })} /></label><label className="grid gap-1 text-sm font-medium text-slate-700">Availability<input className={input} value={selected.availabilityStatus} onChange={(event) => update({ availabilityStatus: event.target.value })} /></label><label className="grid gap-1 text-sm font-medium text-slate-700">Notes<input className={input} value={selected.notes} onChange={(event) => update({ notes: event.target.value })} /></label></div></> : <div className="rounded-lg border border-dashed border-slate-200 bg-slate-50 p-5 text-sm text-slate-600">Select a purchase request with quoted lines.</div>}</section>
    </div>
    <div className="shrink-0 border-t border-slate-200 bg-white p-4"><div className="grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-sm font-medium text-slate-700">Terms<input className={input} name="terms" disabled={!hasFormOptions} /></label><label className="grid gap-1 text-sm font-medium text-slate-700 md:col-span-2">Recording reason<input className={input} name="reason" disabled={!hasFormOptions} required /></label></div><div className="mt-3 text-right"><button className="inline-flex min-h-10 items-center justify-center rounded-md bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700 disabled:bg-slate-300" disabled={!hasFormOptions}>Record Supplier Quote</button></div></div>
  </form>;
}
