export type Phase2WorkflowPolicySeedRow = {
  domain: string;
  action: string;
  fromStatus: string;
  toStatus: string;
  permissionCode: string;
  requiresReason: boolean;
  requiresEvidence: boolean;
  blocksSelfApproval: boolean;
  terminal: boolean;
  active: boolean;
};

export const phase2WorkflowPolicySeedRows = [
  {
    domain: "RECIPE_VERSION",
    action: "SUBMIT",
    fromStatus: "DRAFT",
    toStatus: "SUBMITTED",
    permissionCode: "restaurant.recipe.submit",
    requiresReason: false,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "RECIPE_VERSION",
    action: "START_REVIEW",
    fromStatus: "SUBMITTED",
    toStatus: "UNDER_REVIEW",
    permissionCode: "restaurant.recipe.review",
    requiresReason: false,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "RECIPE_VERSION",
    action: "RETURN",
    fromStatus: "UNDER_REVIEW",
    toStatus: "RETURNED",
    permissionCode: "restaurant.recipe.review",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "RECIPE_VERSION",
    action: "APPROVE",
    fromStatus: "UNDER_REVIEW",
    toStatus: "APPROVED",
    permissionCode: "restaurant.recipe.approve",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: true,
    terminal: false,
    active: true,
  },
  {
    domain: "RECIPE_VERSION",
    action: "PUBLISH",
    fromStatus: "APPROVED",
    toStatus: "PUBLISHED",
    permissionCode: "restaurant.recipe.publish",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: true,
    terminal: true,
    active: true,
  },
  {
    domain: "RECIPE_VERSION",
    action: "REJECT",
    fromStatus: "UNDER_REVIEW",
    toStatus: "REJECTED",
    permissionCode: "restaurant.recipe.review",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "RECIPE_VERSION",
    action: "CANCEL",
    fromStatus: "DRAFT",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.recipe.archive",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MENU_PRICE_DECISION",
    action: "SUBMIT",
    fromStatus: "DRAFT",
    toStatus: "SUBMITTED",
    permissionCode: "restaurant.menu_price.decide",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "MENU_PRICE_DECISION",
    action: "START_REVIEW",
    fromStatus: "SUBMITTED",
    toStatus: "UNDER_REVIEW",
    permissionCode: "restaurant.menu_price.decide",
    requiresReason: false,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "MENU_PRICE_DECISION",
    action: "APPROVE",
    fromStatus: "UNDER_REVIEW",
    toStatus: "APPROVED",
    permissionCode: "restaurant.menu_price.decide",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: true,
    terminal: false,
    active: true,
  },
  {
    domain: "MENU_PRICE_DECISION",
    action: "APPLY",
    fromStatus: "APPROVED",
    toStatus: "APPLIED",
    permissionCode: "restaurant.menu_price.decide",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: true,
    terminal: true,
    active: true,
  },
  {
    domain: "MENU_PRICE_DECISION",
    action: "REJECT",
    fromStatus: "UNDER_REVIEW",
    toStatus: "REJECTED",
    permissionCode: "restaurant.menu_price.decide",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "BRANCH_CHECKLIST",
    action: "START_MANAGER_REVIEW",
    fromStatus: "SUBMITTED",
    toStatus: "MANAGER_REVIEW",
    permissionCode: "restaurant.branch_operations.review",
    requiresReason: false,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "BRANCH_CHECKLIST",
    action: "RETURN_FOR_CORRECTION",
    fromStatus: "MANAGER_REVIEW",
    toStatus: "RETURNED",
    permissionCode: "restaurant.branch_operations.correct",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "BRANCH_CHECKLIST",
    action: "CLOSE",
    fromStatus: "MANAGER_REVIEW",
    toStatus: "CLOSED",
    permissionCode: "restaurant.branch_operations.review",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "FOOD_SAFETY_LOG",
    action: "START_EXCEPTION_REVIEW",
    fromStatus: "SUBMITTED",
    toStatus: "EXCEPTION_REVIEW",
    permissionCode: "restaurant.food_safety.review",
    requiresReason: false,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "FOOD_SAFETY_LOG",
    action: "RETURN_FOR_CORRECTION",
    fromStatus: "EXCEPTION_REVIEW",
    toStatus: "RETURNED",
    permissionCode: "restaurant.food_safety.correct",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "FOOD_SAFETY_LOG",
    action: "CLOSE",
    fromStatus: "EXCEPTION_REVIEW",
    toStatus: "CLOSED",
    permissionCode: "restaurant.food_safety.review",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "RESOLVE",
    fromStatus: "OPEN",
    toStatus: "RESOLVED",
    permissionCode: "restaurant.incident.resolve",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "RESOLVE",
    fromStatus: "IN_PROGRESS",
    toStatus: "RESOLVED",
    permissionCode: "restaurant.incident.resolve",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "RESOLVE",
    fromStatus: "PENDING_REVIEW",
    toStatus: "RESOLVED",
    permissionCode: "restaurant.incident.resolve",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "CANCEL",
    fromStatus: "OPEN",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.incident.resolve",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "CANCEL",
    fromStatus: "IN_PROGRESS",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.incident.resolve",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "CANCEL",
    fromStatus: "PENDING_REVIEW",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.incident.resolve",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "DETAIL_CORRECTION",
    fromStatus: "OPEN",
    toStatus: "OPEN",
    permissionCode: "restaurant.incident.create",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "DETAIL_CORRECTION",
    fromStatus: "IN_PROGRESS",
    toStatus: "IN_PROGRESS",
    permissionCode: "restaurant.incident.create",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "OPERATIONAL_INCIDENT",
    action: "DETAIL_CORRECTION",
    fromStatus: "PENDING_REVIEW",
    toStatus: "PENDING_REVIEW",
    permissionCode: "restaurant.incident.create",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "COMPLETE",
    fromStatus: "OPEN",
    toStatus: "COMPLETED",
    permissionCode: "restaurant.maintenance.complete",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "COMPLETE",
    fromStatus: "IN_PROGRESS",
    toStatus: "COMPLETED",
    permissionCode: "restaurant.maintenance.complete",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "COMPLETE",
    fromStatus: "PENDING_VENDOR",
    toStatus: "COMPLETED",
    permissionCode: "restaurant.maintenance.complete",
    requiresReason: true,
    requiresEvidence: true,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "CANCEL",
    fromStatus: "OPEN",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.maintenance.complete",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "CANCEL",
    fromStatus: "IN_PROGRESS",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.maintenance.complete",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "CANCEL",
    fromStatus: "PENDING_VENDOR",
    toStatus: "CANCELLED",
    permissionCode: "restaurant.maintenance.complete",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: true,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "DETAIL_CORRECTION",
    fromStatus: "OPEN",
    toStatus: "OPEN",
    permissionCode: "restaurant.maintenance.create",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "DETAIL_CORRECTION",
    fromStatus: "IN_PROGRESS",
    toStatus: "IN_PROGRESS",
    permissionCode: "restaurant.maintenance.create",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
  {
    domain: "MAINTENANCE_TICKET",
    action: "DETAIL_CORRECTION",
    fromStatus: "PENDING_VENDOR",
    toStatus: "PENDING_VENDOR",
    permissionCode: "restaurant.maintenance.create",
    requiresReason: true,
    requiresEvidence: false,
    blocksSelfApproval: false,
    terminal: false,
    active: true,
  },
] as const satisfies readonly Phase2WorkflowPolicySeedRow[];
